### ISSUE TITLE
Ansible role installation from Galaxy failing due to SNI cert compatibility

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/docker-ubuntu1404-ansible#2]
See error like:

```
Requirements file detected; installing dependencies.
 [WARNING]: - geerlingguy.repo-remi was NOT installed successfully: Failed to
get data from the API server (https://galaxy.ansible.com/api/): Failed to
validate the SSL certificate for galaxy.ansible.com:443. Make sure your managed
systems have a valid CA certificate installed. If the website serving the url
uses SNI you need python >= 2.7.9 on your managed machine  (the python
executable used (/usr/bin/python) is version: 2.7.6 (default, Nov 23 2017,
15:49:48) [GCC 4.8.4]) or you can install the `urllib3`, `pyOpenSSL`, `ndg-
httpsclient`, and `pyasn1` python modules to perform SNI verification in python
>= 2.6. You can use validate_certs=False if you do not need to confirm the
servers identity but this is unsafe and not recommended. Paths checked for this
platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs,
/usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was:
hostname u'galaxy.ansible.com' doesn't match either of
'*.c1e4.galaxy.openshiftapps.com', 'c1e4.galaxy.openshiftapps.com'.
```

From: https://travis-ci.org/geerlingguy/ansible-role-php/jobs/401320807

**Comment by imrakeshmallik** [comment]
Hi Geerlingguy,

I'm getting following error message, could you please suggest me what could be the reason ?

 [WARNING]: - geerlingguy.git was NOT installed successfully: Failed to get
data from the API server (https://galaxy.ansible.com/api/): Failed to validate
the SSL certificate for galaxy.ansible.com:443. Make sure your managed systems
have a valid CA certificate installed. If the website serving the url uses SNI
you need python >= 2.7.9 on your managed machine  (the python executable used
(/usr/bin/python) is version: 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC
4.8.4]) or you can install the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and
`pyasn1` python modules to perform SNI verification in python >= 2.6. You can
use validate_certs=False if you do not need to confirm the servers identity but
this is unsafe and not recommended. Paths checked for this platform:
/etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share
/ca-certificates/cacert.org, /etc/ansible. The exception msg was: hostname
u'galaxy.ansible.com' doesn't match either of
'*.c1e4.galaxy.openshiftapps.com', 'c1e4.galaxy.openshiftapps.com'.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

**Comment by geerlingguy** [comment]
@imrakeshmallik - you might need to force using `/usr/bin/python2.7` instead of `python` directly, to make sure you're using the newer version of Python installed with this docker image.
