### ISSUE TITLE
Please add repo for debian 7

### ISSUE THREAD

**Issue by AlexGluck** [geerlingguy/docker-ubuntu1404-ansible#3]
I fork this repo and added fix for working with debian 7. You already have many code with hardcode you name and some paths to docker hub and travis. For decrase difficulty supporting all this, can you add please repo for debian 7?
https://github.com/AlexGluck/docker-debian7-ansible

**Comment by geerlingguy** [comment]
I have a Debian 8 and 9 repo: https://github.com/geerlingguy/docker-debian8-ansible/ — but I don't use Debian 7 anymore, so I'm not planning on adding any support for Debian 7 anytime soon.
