### ISSUE TITLE
Maintain 'testing' branch with test tools pre-installed

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/docker-ubuntu1404-ansible#4]
See: https://github.com/geerlingguy/docker-ubuntu1804-ansible/issues/4

Basically, maintain `latest` as-is, but add a `testing` branch which includes Ansible plus:

  - `yamllint`
  - `ansible-lint`
  - `flake8`
  - `testinfra`
  - `molecule`

**Comment by geerlingguy** [comment]
Having some trouble due to system Python being annoying, and the PPA not covering all the devel/etc. Python packages...

**Comment by kso512** [comment]
Hi Jeff,

Thanks for all your hard work on these docker images!

I noticed one of my builds began to fail yesterday, just for Ubuntu 14.04, and upon investigation found that Python seems to be missing from the docker image.

Is your message above possibly related to this error?

```
Running command: docker exec 1540220865 env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml
PLAY [localhost] ***************************************************************
TASK [Gathering Facts] *********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: 1: /usr/bin/python: not found\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 127}
	to retry, use: --limit @/etc/ansible/roles/role_under_test/tests/test.retry
PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```
Full reference:
https://travis-ci.org/kso512/install-check_mk-client/jobs/444553234

Let me know what I can do to help, if anything, and thanks again!
-Chris

**Comment by geerlingguy** [comment]
@kso512 - Yeah, ditto. I'm trying to get it fixed this morning. GitHub's outage has not been helping the situation at all :(

**Comment by geerlingguy** [comment]
Just pushed a new update to the Dockerfile; it should build in the next 30 min to an hour and then may work better.

**Comment by geerlingguy** [comment]
@kso512 - I just re-ran my Docker role tests and they're passing again. Hopefully that fixes things up for you too!

**Comment by kso512** [comment]
@geerlingguy - yes, all green now!  

Much obliged,
-Chris

**Comment by geerlingguy** [comment]
Testing tag is up!
