### ISSUE TITLE
docker image build failure: PPA removed from public access

### ISSUE THREAD

**Issue by gizero** [geerlingguy/docker-ubuntu1404-ansible#5]
A PPA that this project's Dockerfile is using has been removed from public access, causing errors at any `apt-get update` call, either while building the docker image or using it in molecule test scenarios. See https://launchpad.net/~jonathonf/+archive/ubuntu/python-2.7.

**Comment by geerlingguy** [comment]
This image is now deprecated as Ubuntu 14.04 is no longer a supported LTS release. I'll likely add more formal deprecations soon, and archive the project. Closing this issue as a result, but thanks for posting the info!
